node {
  stage(Clone the project) {
    git branch 'main', url 'httpsgithub.comnabilfeghalijenkins-demo.git'
  }

  stage(Compilation) {
    sh .mvnw clean install -DskipTests
  }

  stage(Tests and Deployment) {
    stage(Runing unit tests) {
      sh .mvnw test -Punit
    }
    stage(Deployment) {
      sh 'nohup .mvnw spring-bootrun -Dserver.port=8001 &'
    }
  }
}
