pipeline{
    agent { label 'cbsdev_agent1' }
    tools {
        maven "Maven"
    }
    environment {
        JAVA_HOME="${tool 'Java-1.8'}"
        PROJECT_NAME = sh(script: 'echo $JOB_NAME', returnStdout: true).trim()
		
	echo "JAVA_HOME= ${env.JAVA_HOME}"
        echo "PROJECT_NAME= ${env.PROJECT_NAME}"
		
    }
	
    stages{
	
        stage("Clone from Git"){
            steps{
                // git branch: 'master', credentialsId: 'GitLabCredentials', url:'http://gitlab.capital-banking.com/SwiftManager/MicroService/swiftmxmanagerws.git'
            }
        }
        
        
        stage("Build With Maven") {
            steps {
                // sh 'mvn clean install -U -DskipTests=true'
            }
        }
        
        stage("SonarQube Analysis") {
            steps {
				
            }
        }
        
        stage("Publish to Nexus") {
            steps {
                echo "Start Publish to Nexus"
                script {
				
				}
			}
		}
		
	}
}	
