pipeline{
    agent { label 'cbsdev_agent1' }
    tools {
        maven "Maven"
    }
    environment {
        JAVA_HOME="${tool 'Java-1.8'}"
        PROJECT_NAME = sh(script: 'echo $JOB_NAME', returnStdout: true).trim()
		
		echo "JAVA_HOME: ${JAVA_HOME}"
        echo "PROJECT_NAME: ${PROJECT_NAME}"
		
    }
	
    stages{
	
        stage("Clone from Git"){
            steps{
                // git branch: 'master', credentialsId: 'GitLabCredentials', url:'http://gitlab.capital-banking.com/SwiftManager/MicroService/swiftmxmanagerws.git'
            }
        }
        
        
        stage("Build With Maven") {
            steps {
                // sh 'mvn clean install -U -DskipTests=true'
            }
        }
        
        stage("SonarQube Analysis") {
            steps {
				/*
                withCredentials([usernamePassword(credentialsId: 'SonarCredentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            sonar-scanner \
                              -Dsonar.projectKey=${PROJECT_NAME} \
                              -Dsonar.sources=src \
                              -Dsonar.login=${USERNAME} \
                              -Dsonar.password=${PASSWORD} \
                              -Dsonar.host.url=http://10.1.116.181:9001 \
                              -Dsonar.java.binaries=target/classes \
                              -Dsonar.java.libraries=**/*.jar \
                              -Dsonar.java.source=1.8 \
                              -Dsonar.java.target=1.8
                          """
                    }
                }
				*/
            }
        }
        
        stage("Publish to Nexus") {
            steps {
                echo "Start Publish to Nexus"
                script {
				
				}
			}
		}
		
	}
}	
